import http from 'node:http';
import crypto from 'node:crypto';
import bcrypt from 'bcryptjs';
import jwt from 'jsonwebtoken';
import pg from 'pg';

const {Pool}=pg;
const PORT=Number(process.env.PORT||8787);
const JWT_SECRET=process.env.JWT_SECRET;
if(!process.env.DATABASE_URL||!JWT_SECRET) throw new Error('DATABASE_URL and JWT_SECRET are required');
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_SSL==='true'?{rejectUnauthorized:false}:undefined,max:10});
const allowedOrigin=process.env.CORS_ORIGIN||'';
const jsonHeaders={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'};
const send=(res,status,data,extra={})=>{const out=JSON.stringify(data);res.writeHead(status,{...jsonHeaders,'Content-Length':Buffer.byteLength(out),'Access-Control-Allow-Origin':allowedOrigin||'null','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS',...extra});res.end(out)};
const now=()=>new Date().toISOString();
async function readBody(req){let s='';for await(const c of req){s+=c;if(s.length>2_000_000)throw Error('payload too large')}return s?JSON.parse(s):{}}
function tokenFor(user){return jwt.sign({sub:user.id,email:user.email},JWT_SECRET,{expiresIn:'12h',issuer:'bright-bulk'})}
function auth(req){const h=req.headers.authorization||'';if(!h.startsWith('Bearer '))throw Error('unauthorized');return jwt.verify(h.slice(7),JWT_SECRET,{issuer:'bright-bulk'})}
function render(body,c){return String(body).replace(/\{\{name\}\}/gi,c.name||'عميل').replace(/\{\{phone\}\}/gi,c.phone||'')}
async function api(url,opts={}){const r=await fetch(url,opts);const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={raw:text}};return {ok:r.ok,status:r.status,data}}
async function sendWhatsApp(to,text){const token=process.env.WA_ACCESS_TOKEN,id=process.env.WA_PHONE_NUMBER_ID,ver=process.env.WA_API_VERSION||'v23.0';if(!token||!id)return {ok:false,error:'WhatsApp provider is not configured'};const r=await api(`https://graph.facebook.com/${ver}/${id}/messages`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({messaging_product:'whatsapp',to,type:'text',text:{body:text,preview_url:false}})});return r.ok?{ok:true,providerId:r.data?.messages?.[0]?.id||''}:{ok:false,error:r.data?.error?.message||`HTTP ${r.status}`}}
async function sendTelegram(to,text){const token=process.env.TELEGRAM_BOT_TOKEN;if(!token)return {ok:false,error:'Telegram provider is not configured'};const r=await api(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:to,text})});return r.ok&&r.data.ok!==false?{ok:true,providerId:String(r.data.result?.message_id||'')}:{ok:false,error:r.data?.description||`HTTP ${r.status}`}}
async function deliver(m,c){const target=m.channel==='whatsapp'?String(c.channels?.whatsapp||c.phone).replace(/\D/g,''):String(c.channels?.[m.channel]||'');if(!target)return {ok:false,error:`missing ${m.channel} target`};const text=render(m.body,c);if(m.channel==='whatsapp')return sendWhatsApp(target,text);if(m.channel==='telegram')return sendTelegram(target,text);return {ok:false,error:`${m.channel} requires its official provider adapter`}}
async function claim(){const client=await pool.connect();try{await client.query('BEGIN');const q=await client.query(`SELECT cm.*,c.user_id,c.channel FROM campaign_messages cm JOIN campaigns c ON c.id=cm.campaign_id WHERE cm.status='queued' AND cm.available_at<=now() AND c.status='running' AND (c.schedule_at IS NULL OR c.schedule_at<=now()) ORDER BY cm.created_at LIMIT 1 FOR UPDATE SKIP LOCKED`);if(!q.rowCount){await client.query('COMMIT');return null}const m=q.rows[0];await client.query(`UPDATE campaign_messages SET status='sending',attempts=attempts+1,locked_at=now() WHERE id=$1`,[m.id]);await client.query('COMMIT');return m}finally{client.release()}}
async function work(){let m;try{m=await claim();if(!m)return}catch(e){console.error('queue claim',e);return}const c=await pool.query('SELECT * FROM contacts WHERE id=$1 AND user_id=$2',[m.contact_id,m.user_id]);if(!c.rowCount)return failMessage(m,'contact not found');const result=await deliver(m,c.rows[0]);if(result.ok){await pool.query(`UPDATE campaign_messages SET status='sent',provider_id=$1,sent_at=now(),error=NULL WHERE id=$2`,[result.providerId||'',m.id]);await pool.query(`INSERT INTO messages(user_id,contact_id,channel,direction,external_id,text,status) VALUES($1,$2,$3,'outbound',$4,$5,'sent')`,[m.user_id,m.contact_id,m.channel,result.providerId||'',render(m.body,c.rows[0])])}else{await failMessage(m,result.error)}}
async function failMessage(m,error){const retry=Number(m.attempts)<3;await pool.query(`UPDATE campaign_messages SET status=$1,error=$2,available_at=now()+interval '15 seconds' WHERE id=$3`,[retry?'queued':'failed',error,m.id])}
setInterval(()=>work().catch(console.error),500);
async function route(req,res){if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':allowedOrigin||'null','Access-Control-Allow-Headers':'Content-Type, Authorization','Access-Control-Allow-Methods':'GET,POST,PUT,PATCH,DELETE,OPTIONS'});return res.end()}
 const u=new URL(req.url,`http://${req.headers.host||'localhost'}`);const p=u.pathname;
 try{
  if(req.method==='GET'&&p==='/api/health')return send(res,200,{ok:true,service:'bright-bulk',time:now()});
  if(req.method==='POST'&&p==='/api/auth/register'){const b=await readBody(req);const email=String(b.email||'').trim().toLowerCase();const pass=String(b.password||'');if(!/^\S+@\S+\.\S+$/.test(email)||pass.length<10)return send(res,400,{error:'valid email and password >= 10 chars required'});const hash=await bcrypt.hash(pass,12);const q=await pool.query('INSERT INTO users(email,password_hash) VALUES($1,$2) RETURNING id,email',[email,hash]);return send(res,201,{user:q.rows[0],token:tokenFor(q.rows[0])})}
  if(req.method==='POST'&&p==='/api/auth/login'){const b=await readBody(req);const q=await pool.query('SELECT id,email,password_hash FROM users WHERE email=$1',[String(b.email||'').trim().toLowerCase()]);if(!q.rowCount||!(await bcrypt.compare(String(b.password||''),q.rows[0].password_hash)))return send(res,401,{error:'invalid credentials'});const user={id:q.rows[0].id,email:q.rows[0].email};return send(res,200,{user,token:tokenFor(user)})}
  if(req.method==='GET'&&p==='/api/webhooks/whatsapp'){const mode=u.searchParams.get('hub.mode'),verify=u.searchParams.get('hub.verify_token'),challenge=u.searchParams.get('hub.challenge');if(mode==='subscribe'&&verify===process.env.WA_VERIFY_TOKEN)return send(res,200,{challenge});return send(res,403,{error:'verification failed'})}
  let user=null;if(p.startsWith('/api/')&&!p.startsWith('/api/auth/')&&!p.startsWith('/api/webhooks/'))user=auth(req);
  if(req.method==='GET'&&p==='/api/contacts'){const q=await pool.query('SELECT id,name,phone,tags,channels,created_at,updated_at FROM contacts WHERE user_id=$1 ORDER BY created_at DESC',[user.sub]);return send(res,200,{contacts:q.rows})}
  if(req.method==='POST'&&p==='/api/contacts'){const b=await readBody(req);const id=b.id||crypto.randomUUID();const q=await pool.query(`INSERT INTO contacts(id,user_id,name,phone,tags,channels) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id,phone) DO UPDATE SET name=EXCLUDED.name,tags=EXCLUDED.tags,channels=EXCLUDED.channels,updated_at=now() RETURNING *`,[id,user.sub,String(b.name||'عميل'),String(b.phone||''),JSON.stringify(Array.isArray(b.tags)?b.tags:[]),JSON.stringify(b.channels||{})]);return send(res,201,q.rows[0])}
  if(req.method==='POST'&&p==='/api/contacts/bulk'){const b=await readBody(req);let n=0;for(const x of (Array.isArray(b.contacts)?b.contacts:[])){await pool.query(`INSERT INTO contacts(id,user_id,name,phone,tags,channels) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(user_id,phone) DO UPDATE SET name=EXCLUDED.name,tags=EXCLUDED.tags,channels=EXCLUDED.channels,updated_at=now()`,[x.id||crypto.randomUUID(),user.sub,String(x.name||'عميل'),String(x.phone||''),JSON.stringify(x.tags||[]),JSON.stringify(x.channels||{})]);n++}return send(res,201,{created:n})}
  if(req.method==='GET'&&p==='/api/campaigns'){const q=await pool.query(`SELECT c.*,count(cm.id) FILTER(WHERE cm.status='sent') sent,count(cm.id) total FROM campaigns c LEFT JOIN campaign_messages cm ON cm.campaign_id=c.id WHERE c.user_id=$1 GROUP BY c.id ORDER BY c.created_at DESC`,[user.sub]);return send(res,200,{campaigns:q.rows})}
  if(req.method==='POST'&&p==='/api/campaigns'){const b=await readBody(req);const client=await pool.connect();try{await client.query('BEGIN');const c=await client.query(`INSERT INTO campaigns(id,user_id,name,channel,body,delay_ms,schedule_at) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING *`,[b.id||crypto.randomUUID(),user.sub,String(b.name||'Campaign'),String(b.channel||'whatsapp'),String(b.body||''),Math.max(500,Number(b.delayMs||2000)),b.scheduleAt||null]);const ids=Array.isArray(b.contactIds)?b.contactIds:[];if(ids.length)await client.query(`INSERT INTO campaign_messages(campaign_id,contact_id,body) SELECT $1,id,$2 FROM contacts WHERE user_id=$3 AND id=ANY($4::uuid[])`,[c.rows[0].id,String(b.body||''),user.sub,ids]);await client.query('COMMIT');return send(res,201,c.rows[0])}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}}
  const cm=p.match(/^\/api\/campaigns\/([0-9a-f-]+)\/(start|pause|resume|stop)$/);if(req.method==='POST'&&cm){const id=cm[1],action=cm[2];const status=action==='pause'?'paused':action==='stop'?'stopped':'running';const q=await pool.query('UPDATE campaigns SET status=$1,updated_at=now() WHERE id=$2 AND user_id=$3 RETURNING *',[status,id,user.sub]);if(!q.rowCount)return send(res,404,{error:'campaign not found'});return send(res,200,q.rows[0])}
  if(req.method==='GET'&&p==='/api/inbox'){const q=await pool.query('SELECT id,contact_id,channel,direction,external_id,text,status,created_at FROM messages WHERE user_id=$1 ORDER BY created_at DESC LIMIT 500',[user.sub]);return send(res,200,{messages:q.rows})}
  if(req.method==='GET'&&p==='/api/templates'){const q=await pool.query('SELECT * FROM templates WHERE user_id=$1 ORDER BY created_at DESC',[user.sub]);return send(res,200,{templates:q.rows})}
  if(req.method==='POST'&&p==='/api/templates'){const b=await readBody(req);const q=await pool.query('INSERT INTO templates(user_id,name,channel,body) VALUES($1,$2,$3,$4) RETURNING *',[user.sub,String(b.name||'Template'),String(b.channel||'whatsapp'),String(b.body||'')]);return send(res,201,q.rows[0])}
  if(req.method==='POST'&&p==='/api/webhooks/inbound'){const b=await readBody(req);if(!b.channel||!b.externalId)return send(res,400,{error:'channel and externalId required'});const userId=b.userId||process.env.DEFAULT_USER_ID;if(!userId)return send(res,400,{error:'webhook owner not configured'});const eid=String(b.eventId||crypto.createHash('sha256').update(JSON.stringify(b)).digest('hex'));const ins=await pool.query('INSERT INTO webhook_events(id,user_id,channel,payload) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING RETURNING id',[eid,userId,b.channel,b]);if(!ins.rowCount)return send(res,200,{ok:true,duplicate:true});const c=await pool.query('SELECT id FROM contacts WHERE user_id=$1 AND (phone=$2 OR channels->>$3=$2) LIMIT 1',[userId,String(b.externalId),b.channel]);if(c.rowCount)await pool.query('INSERT INTO messages(user_id,contact_id,channel,direction,external_id,text,status) VALUES($1,$2,$3,\'inbound\',$4,$5,\'received\')',[userId,c.rows[0].id,b.channel,String(b.externalId),String(b.text||'')]);return send(res,200,{ok:true})}
  return send(res,404,{error:'not found'});
 }catch(e){console.error(e);return send(res,e.message==='unauthorized'?401:500,{error:e.message||'server error'})}}
http.createServer(route).listen(PORT,'0.0.0.0',()=>console.log(`Bright Bulk API listening on :${PORT}`));
